//KONTRAK KOMUNIKASI ANTAR SERVICE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: lab.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	EnvType       string                 `protobuf:"bytes,2,opt,name=env_type,json=envType,proto3" json:"env_type,omitempty"` // e.g., "DataScience_Python"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvRequest) Reset() {
	*x = EnvRequest{}
	mi := &file_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvRequest) ProtoMessage() {}

func (x *EnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvRequest.ProtoReflect.Descriptor instead.
func (*EnvRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{0}
}

func (x *EnvRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnvRequest) GetEnvType() string {
	if x != nil {
		return x.EnvType
	}
	return ""
}

type EnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvResponse) Reset() {
	*x = EnvResponse{}
	mi := &file_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvResponse) ProtoMessage() {}

func (x *EnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvResponse.ProtoReflect.Descriptor instead.
func (*EnvResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{1}
}

func (x *EnvResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnvResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProvisionJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionJob) Reset() {
	*x = ProvisionJob{}
	mi := &file_lab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionJob) ProtoMessage() {}

func (x *ProvisionJob) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionJob.ProtoReflect.Descriptor instead.
func (*ProvisionJob) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogUpdate) Reset() {
	*x = LogUpdate{}
	mi := &file_lab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogUpdate) ProtoMessage() {}

func (x *LogUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogUpdate.ProtoReflect.Descriptor instead.
func (*LogUpdate) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{3}
}

func (x *LogUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *LogUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ServerMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMetric) Reset() {
	*x = ServerMetric{}
	mi := &file_lab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetric) ProtoMessage() {}

func (x *ServerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetric.ProtoReflect.Descriptor instead.
func (*ServerMetric) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMetric) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerMetric) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServerMetric) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

type MetricAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricAck) Reset() {
	*x = MetricAck{}
	mi := &file_lab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAck) ProtoMessage() {}

func (x *MetricAck) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAck.ProtoReflect.Descriptor instead.
func (*MetricAck) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{5}
}

func (x *MetricAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_lab_proto protoreflect.FileDescriptor

const file_lab_proto_rawDesc = "" +
	"\n" +
	"\tlab.proto\x12\x03lab\"F\n" +
	"\n" +
	"EnvRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x19\n" +
	"\benv_type\x18\x02 \x01(\tR\aenvType\">\n" +
	"\vEnvResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\fProvisionJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"?\n" +
	"\tLogUpdate\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"e\n" +
	"\fServerMetric\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\"%\n" +
	"\tMetricAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb7\x01\n" +
	"\n" +
	"LabService\x127\n" +
	"\x12RequestEnvironment\x12\x0f.lab.EnvRequest\x1a\x10.lab.EnvResponse\x12:\n" +
	"\x13MonitorProvisioning\x12\x11.lab.ProvisionJob\x1a\x0e.lab.LogUpdate0\x01\x124\n" +
	"\rReportMetrics\x12\x11.lab.ServerMetric\x1a\x0e.lab.MetricAck(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_lab_proto_rawDescOnce sync.Once
	file_lab_proto_rawDescData []byte
)

func file_lab_proto_rawDescGZIP() []byte {
	file_lab_proto_rawDescOnce.Do(func() {
		file_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)))
	})
	return file_lab_proto_rawDescData
}

var file_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lab_proto_goTypes = []any{
	(*EnvRequest)(nil),   // 0: lab.EnvRequest
	(*EnvResponse)(nil),  // 1: lab.EnvResponse
	(*ProvisionJob)(nil), // 2: lab.ProvisionJob
	(*LogUpdate)(nil),    // 3: lab.LogUpdate
	(*ServerMetric)(nil), // 4: lab.ServerMetric
	(*MetricAck)(nil),    // 5: lab.MetricAck
}
var file_lab_proto_depIdxs = []int32{
	0, // 0: lab.LabService.RequestEnvironment:input_type -> lab.EnvRequest
	2, // 1: lab.LabService.MonitorProvisioning:input_type -> lab.ProvisionJob
	4, // 2: lab.LabService.ReportMetrics:input_type -> lab.ServerMetric
	1, // 3: lab.LabService.RequestEnvironment:output_type -> lab.EnvResponse
	3, // 4: lab.LabService.MonitorProvisioning:output_type -> lab.LogUpdate
	5, // 5: lab.LabService.ReportMetrics:output_type -> lab.MetricAck
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lab_proto_init() }
func file_lab_proto_init() {
	if File_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lab_proto_goTypes,
		DependencyIndexes: file_lab_proto_depIdxs,
		MessageInfos:      file_lab_proto_msgTypes,
	}.Build()
	File_lab_proto = out.File
	file_lab_proto_goTypes = nil
	file_lab_proto_depIdxs = nil
}
