//KONTRAK KOMUNIKASI ANTAR SERVICE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: lab.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{0}
}

type ActiveJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	EnvType       string                 `protobuf:"bytes,3,opt,name=env_type,json=envType,proto3" json:"env_type,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveJob) Reset() {
	*x = ActiveJob{}
	mi := &file_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveJob) ProtoMessage() {}

func (x *ActiveJob) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveJob.ProtoReflect.Descriptor instead.
func (*ActiveJob) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ActiveJob) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ActiveJob) GetEnvType() string {
	if x != nil {
		return x.EnvType
	}
	return ""
}

func (x *ActiveJob) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ActiveJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActiveJob) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type LabStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvailableCpu  float32                `protobuf:"fixed32,1,opt,name=available_cpu,json=availableCpu,proto3" json:"available_cpu,omitempty"`
	AvailableRam  float32                `protobuf:"fixed32,2,opt,name=available_ram,json=availableRam,proto3" json:"available_ram,omitempty"`
	ActiveJobs    []*ActiveJob           `protobuf:"bytes,3,rep,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabStatusResponse) Reset() {
	*x = LabStatusResponse{}
	mi := &file_lab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabStatusResponse) ProtoMessage() {}

func (x *LabStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabStatusResponse.ProtoReflect.Descriptor instead.
func (*LabStatusResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{2}
}

func (x *LabStatusResponse) GetAvailableCpu() float32 {
	if x != nil {
		return x.AvailableCpu
	}
	return 0
}

func (x *LabStatusResponse) GetAvailableRam() float32 {
	if x != nil {
		return x.AvailableRam
	}
	return 0
}

func (x *LabStatusResponse) GetActiveJobs() []*ActiveJob {
	if x != nil {
		return x.ActiveJobs
	}
	return nil
}

type EnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	EnvType       string                 `protobuf:"bytes,2,opt,name=env_type,json=envType,proto3" json:"env_type,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"` // e.g., "DataScience_Python"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvRequest) Reset() {
	*x = EnvRequest{}
	mi := &file_lab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvRequest) ProtoMessage() {}

func (x *EnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvRequest.ProtoReflect.Descriptor instead.
func (*EnvRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{3}
}

func (x *EnvRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnvRequest) GetEnvType() string {
	if x != nil {
		return x.EnvType
	}
	return ""
}

func (x *EnvRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type EnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvResponse) Reset() {
	*x = EnvResponse{}
	mi := &file_lab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvResponse) ProtoMessage() {}

func (x *EnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvResponse.ProtoReflect.Descriptor instead.
func (*EnvResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{4}
}

func (x *EnvResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnvResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProvisionJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionJob) Reset() {
	*x = ProvisionJob{}
	mi := &file_lab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionJob) ProtoMessage() {}

func (x *ProvisionJob) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionJob.ProtoReflect.Descriptor instead.
func (*ProvisionJob) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogUpdate) Reset() {
	*x = LogUpdate{}
	mi := &file_lab_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogUpdate) ProtoMessage() {}

func (x *LogUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogUpdate.ProtoReflect.Descriptor instead.
func (*LogUpdate) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{6}
}

func (x *LogUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *LogUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ServerMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMetric) Reset() {
	*x = ServerMetric{}
	mi := &file_lab_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetric) ProtoMessage() {}

func (x *ServerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetric.ProtoReflect.Descriptor instead.
func (*ServerMetric) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMetric) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerMetric) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServerMetric) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

type MetricAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricAck) Reset() {
	*x = MetricAck{}
	mi := &file_lab_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAck) ProtoMessage() {}

func (x *MetricAck) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAck.ProtoReflect.Descriptor instead.
func (*MetricAck) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{8}
}

func (x *MetricAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_lab_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{9}
}

func (x *TerminateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_lab_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{10}
}

func (x *TerminateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_lab_proto protoreflect.FileDescriptor

const file_lab_proto_rawDesc = "" +
	"\n" +
	"\tlab.proto\x12\x03lab\"\a\n" +
	"\x05Empty\"\xad\x01\n" +
	"\tActiveJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x19\n" +
	"\benv_type\x18\x03 \x01(\tR\aenvType\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\"\x8e\x01\n" +
	"\x11LabStatusResponse\x12#\n" +
	"\ravailable_cpu\x18\x01 \x01(\x02R\favailableCpu\x12#\n" +
	"\ravailable_ram\x18\x02 \x01(\x02R\favailableRam\x12/\n" +
	"\vactive_jobs\x18\x03 \x03(\v2\x0e.lab.ActiveJobR\n" +
	"activeJobs\"`\n" +
	"\n" +
	"EnvRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x19\n" +
	"\benv_type\x18\x02 \x01(\tR\aenvType\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\">\n" +
	"\vEnvResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\fProvisionJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"?\n" +
	"\tLogUpdate\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"e\n" +
	"\fServerMetric\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\"%\n" +
	"\tMetricAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x10TerminateRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"-\n" +
	"\x11TerminateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb2\x02\n" +
	"\n" +
	"LabService\x127\n" +
	"\x12RequestEnvironment\x12\x0f.lab.EnvRequest\x1a\x10.lab.EnvResponse\x12:\n" +
	"\x13MonitorProvisioning\x12\x11.lab.ProvisionJob\x1a\x0e.lab.LogUpdate0\x01\x124\n" +
	"\rReportMetrics\x12\x11.lab.ServerMetric\x1a\x0e.lab.MetricAck(\x01\x122\n" +
	"\fGetLabStatus\x12\n" +
	".lab.Empty\x1a\x16.lab.LabStatusResponse\x12E\n" +
	"\x14TerminateEnvironment\x12\x15.lab.TerminateRequest\x1a\x16.lab.TerminateResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_lab_proto_rawDescOnce sync.Once
	file_lab_proto_rawDescData []byte
)

func file_lab_proto_rawDescGZIP() []byte {
	file_lab_proto_rawDescOnce.Do(func() {
		file_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)))
	})
	return file_lab_proto_rawDescData
}

var file_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lab_proto_goTypes = []any{
	(*Empty)(nil),             // 0: lab.Empty
	(*ActiveJob)(nil),         // 1: lab.ActiveJob
	(*LabStatusResponse)(nil), // 2: lab.LabStatusResponse
	(*EnvRequest)(nil),        // 3: lab.EnvRequest
	(*EnvResponse)(nil),       // 4: lab.EnvResponse
	(*ProvisionJob)(nil),      // 5: lab.ProvisionJob
	(*LogUpdate)(nil),         // 6: lab.LogUpdate
	(*ServerMetric)(nil),      // 7: lab.ServerMetric
	(*MetricAck)(nil),         // 8: lab.MetricAck
	(*TerminateRequest)(nil),  // 9: lab.TerminateRequest
	(*TerminateResponse)(nil), // 10: lab.TerminateResponse
}
var file_lab_proto_depIdxs = []int32{
	1,  // 0: lab.LabStatusResponse.active_jobs:type_name -> lab.ActiveJob
	3,  // 1: lab.LabService.RequestEnvironment:input_type -> lab.EnvRequest
	5,  // 2: lab.LabService.MonitorProvisioning:input_type -> lab.ProvisionJob
	7,  // 3: lab.LabService.ReportMetrics:input_type -> lab.ServerMetric
	0,  // 4: lab.LabService.GetLabStatus:input_type -> lab.Empty
	9,  // 5: lab.LabService.TerminateEnvironment:input_type -> lab.TerminateRequest
	4,  // 6: lab.LabService.RequestEnvironment:output_type -> lab.EnvResponse
	6,  // 7: lab.LabService.MonitorProvisioning:output_type -> lab.LogUpdate
	8,  // 8: lab.LabService.ReportMetrics:output_type -> lab.MetricAck
	2,  // 9: lab.LabService.GetLabStatus:output_type -> lab.LabStatusResponse
	10, // 10: lab.LabService.TerminateEnvironment:output_type -> lab.TerminateResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_lab_proto_init() }
func file_lab_proto_init() {
	if File_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lab_proto_goTypes,
		DependencyIndexes: file_lab_proto_depIdxs,
		MessageInfos:      file_lab_proto_msgTypes,
	}.Build()
	File_lab_proto = out.File
	file_lab_proto_goTypes = nil
	file_lab_proto_depIdxs = nil
}
