//KONTRAK KOMUNIKASI ANTAR SERVICE

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: lab.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LabService_RequestEnvironment_FullMethodName   = "/lab.LabService/RequestEnvironment"
	LabService_MonitorProvisioning_FullMethodName  = "/lab.LabService/MonitorProvisioning"
	LabService_ReportMetrics_FullMethodName        = "/lab.LabService/ReportMetrics"
	LabService_GetLabStatus_FullMethodName         = "/lab.LabService/GetLabStatus"
	LabService_TerminateEnvironment_FullMethodName = "/lab.LabService/TerminateEnvironment"
)

// LabServiceClient is the client API for LabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabServiceClient interface {
	// Unary: Mahasiswa request lingkungan baru
	RequestEnvironment(ctx context.Context, in *EnvRequest, opts ...grpc.CallOption) (*EnvResponse, error)
	// Server-side Streaming: Update progress provisioning
	MonitorProvisioning(ctx context.Context, in *ProvisionJob, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogUpdate], error)
	// Client-side Streaming: Agent lapor metrik secara berkala
	ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ServerMetric, MetricAck], error)
	// Unary: Status seluruh agent
	GetLabStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LabStatusResponse, error)
	// Unary: Hapus environment
	TerminateEnvironment(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
}

type labServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLabServiceClient(cc grpc.ClientConnInterface) LabServiceClient {
	return &labServiceClient{cc}
}

func (c *labServiceClient) RequestEnvironment(ctx context.Context, in *EnvRequest, opts ...grpc.CallOption) (*EnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvResponse)
	err := c.cc.Invoke(ctx, LabService_RequestEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labServiceClient) MonitorProvisioning(ctx context.Context, in *ProvisionJob, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LabService_ServiceDesc.Streams[0], LabService_MonitorProvisioning_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProvisionJob, LogUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabService_MonitorProvisioningClient = grpc.ServerStreamingClient[LogUpdate]

func (c *labServiceClient) ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ServerMetric, MetricAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LabService_ServiceDesc.Streams[1], LabService_ReportMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerMetric, MetricAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabService_ReportMetricsClient = grpc.ClientStreamingClient[ServerMetric, MetricAck]

func (c *labServiceClient) GetLabStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LabStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LabStatusResponse)
	err := c.cc.Invoke(ctx, LabService_GetLabStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labServiceClient) TerminateEnvironment(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, LabService_TerminateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabServiceServer is the server API for LabService service.
// All implementations must embed UnimplementedLabServiceServer
// for forward compatibility.
type LabServiceServer interface {
	// Unary: Mahasiswa request lingkungan baru
	RequestEnvironment(context.Context, *EnvRequest) (*EnvResponse, error)
	// Server-side Streaming: Update progress provisioning
	MonitorProvisioning(*ProvisionJob, grpc.ServerStreamingServer[LogUpdate]) error
	// Client-side Streaming: Agent lapor metrik secara berkala
	ReportMetrics(grpc.ClientStreamingServer[ServerMetric, MetricAck]) error
	// Unary: Status seluruh agent
	GetLabStatus(context.Context, *Empty) (*LabStatusResponse, error)
	// Unary: Hapus environment
	TerminateEnvironment(context.Context, *TerminateRequest) (*TerminateResponse, error)
	mustEmbedUnimplementedLabServiceServer()
}

// UnimplementedLabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabServiceServer struct{}

func (UnimplementedLabServiceServer) RequestEnvironment(context.Context, *EnvRequest) (*EnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestEnvironment not implemented")
}
func (UnimplementedLabServiceServer) MonitorProvisioning(*ProvisionJob, grpc.ServerStreamingServer[LogUpdate]) error {
	return status.Error(codes.Unimplemented, "method MonitorProvisioning not implemented")
}
func (UnimplementedLabServiceServer) ReportMetrics(grpc.ClientStreamingServer[ServerMetric, MetricAck]) error {
	return status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedLabServiceServer) GetLabStatus(context.Context, *Empty) (*LabStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLabStatus not implemented")
}
func (UnimplementedLabServiceServer) TerminateEnvironment(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateEnvironment not implemented")
}
func (UnimplementedLabServiceServer) mustEmbedUnimplementedLabServiceServer() {}
func (UnimplementedLabServiceServer) testEmbeddedByValue()                    {}

// UnsafeLabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabServiceServer will
// result in compilation errors.
type UnsafeLabServiceServer interface {
	mustEmbedUnimplementedLabServiceServer()
}

func RegisterLabServiceServer(s grpc.ServiceRegistrar, srv LabServiceServer) {
	// If the following call panics, it indicates UnimplementedLabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LabService_ServiceDesc, srv)
}

func _LabService_RequestEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabServiceServer).RequestEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabService_RequestEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabServiceServer).RequestEnvironment(ctx, req.(*EnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabService_MonitorProvisioning_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvisionJob)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LabServiceServer).MonitorProvisioning(m, &grpc.GenericServerStream[ProvisionJob, LogUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabService_MonitorProvisioningServer = grpc.ServerStreamingServer[LogUpdate]

func _LabService_ReportMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LabServiceServer).ReportMetrics(&grpc.GenericServerStream[ServerMetric, MetricAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabService_ReportMetricsServer = grpc.ClientStreamingServer[ServerMetric, MetricAck]

func _LabService_GetLabStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabServiceServer).GetLabStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabService_GetLabStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabServiceServer).GetLabStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabService_TerminateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabServiceServer).TerminateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabService_TerminateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabServiceServer).TerminateEnvironment(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LabService_ServiceDesc is the grpc.ServiceDesc for LabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lab.LabService",
	HandlerType: (*LabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestEnvironment",
			Handler:    _LabService_RequestEnvironment_Handler,
		},
		{
			MethodName: "GetLabStatus",
			Handler:    _LabService_GetLabStatus_Handler,
		},
		{
			MethodName: "TerminateEnvironment",
			Handler:    _LabService_TerminateEnvironment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorProvisioning",
			Handler:       _LabService_MonitorProvisioning_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportMetrics",
			Handler:       _LabService_ReportMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "lab.proto",
}
